### ISSUE TITLE
Not having much luck installing on Mac so far...

### ISSUE THREAD

**Issue by BeggarsMattM** [evansendra/mingit#9] opened 2016-10-19 10:13 UTC
npm install failed with "Error: Command failed: /usr/local/lib/node_modules/mingit/scripts/install-apple-bash-profile.sh"

yarn worked better but running the script resulted in:

line 2790: syntax error near unexpected token `('

line 2790: `g()'

**Comment by evansendra** [comment] 2016-10-19 10:22
I'll be sure to look into what could cause this.  Can you tell me what type of mac you have (hardware / OS version)?  Also, if you just want to use this alias right now, feel free to follow the manual install instructions.  Thanks for reporting!

**Comment by BeggarsMattM** [comment] 2016-10-19 10:34
Thank you, will do! I just upgraded (2015 iMac) to Sierra yesterday so I may have brought this on myself.

**Comment by evansendra** [comment] 2016-10-19 10:39
No problem...go ahead and give it another try...I just did a simple thing and changed the bash function from:

```
g()
{ 
...
```

to 

```
g ()
{
...
```

which may solve it.  Since I can't reproduce this on my machine it may be hard to debug.

**Comment by evansendra** [comment] 2016-10-19 11:21
@BeggarsMattM , if you have some extra time, feel free to uninstall (via `npm uninstall -g mingit` or removing the _~/.mingit.sh_ file as well as the variable added to _~/.bash_profile_) and re-install this with npm.  I'll close this issue for now, but please do re-open if you do the above and discover more errors :)

**Closed as completed** 2016-10-19 11:21 UTC
